/**
 * presets.js — ESKit 組み込みテーマプリセット & 壁紙プリセット
 */

export const THEME_PRESETS = [
  {
    id: "default-dark",
    name: "Default Dark",
    dark: true,
    vars: {
      "--kit-color-primary": "#1e8fff",
      "--kit-color-primary-fg": "#ffffff",
      "--kit-bg": "#1a1a2e",
      "--kit-bg-secondary": "#252540",
      "--kit-bg-tertiary": "#2f2f4a",
      "--kit-fg": "#e0e0e0",
      "--kit-fg-secondary": "#a0a0b0",
      "--kit-fg-tertiary": "#707080",
      "--kit-border-color": "#404060",
      "--kit-border-color-light": "#353550",
    },
    wallpaper: "radial-gradient(ellipse at top, #252540 0%, #121220 100%)",
  },
  {
    id: "default-light",
    name: "Default Light",
    dark: false,
    vars: {
      "--kit-color-primary": "#1e8fff",
      "--kit-color-primary-fg": "#ffffff",
      "--kit-bg": "#ffffff",
      "--kit-bg-secondary": "#f5f5f5",
      "--kit-bg-tertiary": "#e8e8e8",
      "--kit-fg": "#3d3d3d",
      "--kit-fg-secondary": "#6c6c6c",
      "--kit-fg-tertiary": "#909090",
      "--kit-border-color": "#d0d0d0",
      "--kit-border-color-light": "#e0e0e0",
    },
    wallpaper: "radial-gradient(ellipse at top, #e8eff8 0%, #d5e2f0 100%)",
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    dark: true,
    vars: {
      "--kit-color-primary": "#cba6f7",
      "--kit-color-primary-fg": "#11111b",
      "--kit-bg": "#1e1e2e",
      "--kit-bg-secondary": "#181825",
      "--kit-bg-tertiary": "#313244",
      "--kit-fg": "#cdd6f4",
      "--kit-fg-secondary": "#a6adc8",
      "--kit-fg-tertiary": "#6c7086",
      "--kit-border-color": "#45475a",
      "--kit-border-color-light": "#313244",
    },
    wallpaper: "linear-gradient(135deg, #1e1e2e 0%, #11111b 100%)",
  },
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    dark: false,
    vars: {
      "--kit-color-primary": "#8839ef",
      "--kit-color-primary-fg": "#ffffff",
      "--kit-bg": "#eff1f5",
      "--kit-bg-secondary": "#e6e9ef",
      "--kit-bg-tertiary": "#dce0e8",
      "--kit-fg": "#4c4f69",
      "--kit-fg-secondary": "#6c6f85",
      "--kit-fg-tertiary": "#9ca0b0",
      "--kit-border-color": "#bcc0cc",
      "--kit-border-color-light": "#ccd0da",
    },
    wallpaper: "linear-gradient(135deg, #eff1f5 0%, #dce0e8 100%)",
  },
  {
    id: "nord",
    name: "Nord",
    dark: true,
    vars: {
      "--kit-color-primary": "#88c0d0",
      "--kit-color-primary-fg": "#2e3440",
      "--kit-bg": "#2e3440",
      "--kit-bg-secondary": "#3b4252",
      "--kit-bg-tertiary": "#434c5e",
      "--kit-fg": "#eceff4",
      "--kit-fg-secondary": "#d8dee9",
      "--kit-fg-tertiary": "#4c566a",
      "--kit-border-color": "#4c566a",
      "--kit-border-color-light": "#3b4252",
    },
    wallpaper: "radial-gradient(ellipse at bottom, #3b4252 0%, #242933 100%)",
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    dark: true,
    vars: {
      "--kit-color-primary": "#7aa2f7",
      "--kit-color-primary-fg": "#1a1b26",
      "--kit-bg": "#1a1b26",
      "--kit-bg-secondary": "#16161e",
      "--kit-bg-tertiary": "#24283b",
      "--kit-fg": "#c0caf5",
      "--kit-fg-secondary": "#9aa5ce",
      "--kit-fg-tertiary": "#565f89",
      "--kit-border-color": "#292e42",
      "--kit-border-color-light": "#1f2335",
    },
    wallpaper: "linear-gradient(135deg, #1a1b26 0%, #101018 100%)",
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    dark: true,
    vars: {
      "--kit-color-primary": "#268bd2",
      "--kit-color-primary-fg": "#ffffff",
      "--kit-bg": "#002b36",
      "--kit-bg-secondary": "#073642",
      "--kit-bg-tertiary": "#0a4352",
      "--kit-fg": "#839496",
      "--kit-fg-secondary": "#93a1a1",
      "--kit-fg-tertiary": "#586e75",
      "--kit-border-color": "#073642",
      "--kit-border-color-light": "#0a4352",
    },
    wallpaper: "linear-gradient(135deg, #002b36 0%, #001f27 100%)",
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    dark: false,
    vars: {
      "--kit-color-primary": "#268bd2",
      "--kit-color-primary-fg": "#ffffff",
      "--kit-bg": "#fdf6e3",
      "--kit-bg-secondary": "#eee8d5",
      "--kit-bg-tertiary": "#e0d9c4",
      "--kit-fg": "#657b83",
      "--kit-fg-secondary": "#586e75",
      "--kit-fg-tertiary": "#93a1a1",
      "--kit-border-color": "#d3368222",
      "--kit-border-color-light": "#eee8d5",
    },
    wallpaper: "linear-gradient(135deg, #fdf6e3 0%, #eee8d5 100%)",
  },
];

export const WALLPAPER_PRESETS = [
  {
    id: "default-space",
    name: "Deep Space",
    value: "radial-gradient(ellipse at top, #252540 0%, #121220 100%)",
  },
  {
    id: "soft-sky",
    name: "Soft Sky",
    value: "radial-gradient(ellipse at top, #e8eff8 0%, #d5e2f0 100%)",
  },
  {
    id: "aurora",
    name: "Nord Aurora",
    value: "linear-gradient(135deg, #2e3440 0%, #3b4252 50%, #434c5e 100%)",
  },
  {
    id: "sunset-glow",
    name: "Sunset Glow",
    value: "linear-gradient(135deg, #2d1b4e 0%, #1c1335 50%, #0d091a 100%)",
  },
  {
    id: "emerald-night",
    name: "Emerald Night",
    value: "linear-gradient(135deg, #0b2520 0%, #051411 100%)",
  },
  {
    id: "clean-slate",
    name: "Clean Slate",
    value: "linear-gradient(135deg, #181926 0%, #24273a 100%)",
  },
];
